### ISSUE TITLE
Add a fat file-level comment that explains the high-level workings of prop259.c

### ISSUE THREAD

**Issue by iapazmino** [twstrike/tor_for_patching#15]

**Comment by iapazmino** [comment]
@asn-the-goblin-slayer  Should this be enough to close the issue?

**Comment by asn-d6** [comment]
Hm, I was expecting some more high-level implementation details in the comment (e.g. see the file-level comment in `src/or/transports.c`).

For example, details on how the public API of prop259.c works. Or what `guard_selection_t` is, and how it's used. How retries are handled. How long do guards need to be down to get removed from the lists, etc.

If you think these things don't need to be explained, or are explained somewhere else, then the comment you added should be sufficient, yes.

Thanks :)

**Comment by tcz001** [comment]
@iapazmino I can help with this, could you please confirm or split up the work if you've been starting with the issue?
