### ISSUE TITLE
Support directory guards

### ISSUE THREAD

**Issue by juniorz** [twstrike/tor_for_patching#2]
We have decided to keep using the same sampled sets to choose directory guards from, and assume the samples will contain directory guards.

The assumption is based on the idea that in the near future, all entry guards will also be directory guards.

This issue then is about sending the `for_directory` parameter to `START()` and filtering out non directory guards in such case.

**Comment by tdruiva** [comment]
In Tor, we initialize our algorithm in two places:
- when we `choose_random_entry`
- when we `choose_random_dirguard`

So I think we can track this necessity (to use dir) thought INIT() and then when we filter the possible guards, we can exclude who is not DIR if it's requested

**Comment by tcz001** [comment]
Can we just validate the guard filtered according to this flag before return?
Because filtered guards are not persisted, and if most guards are DIRable guards, we can use the same sample set.

**Comment by tdruiva** [comment]
:+1:

**Comment by tcz001** [comment]
We have decided to filter only directory, stable and fast nodes
