### ISSUE TITLE
Is choose_random_entry_impl the right place to put the proposal?

### ISSUE THREAD

**Issue by juniorz** [twstrike/tor_for_patching#3]
For the first test, I've replaced `choose_random_entry_impl` entirely by a wrapper around the proposal (to keep the existing API).

The concern here is making sure we keep the existing relevant conditions/constraints in the current `choose_random_entry_impl`. This is the call graph for `choose_random_entry_impl`:

```
choose_random_entry_impl
|- pick_entry_guards (this is roughly equivalent to our sampled sets)
  |- add_an_entry_guard
    |- choose_good_entry_server (for entry guard)
      |- choose_random_entry (happy path)
      |- router_choose_random_node (alternative path when UseEntryGuards = 0)
    |- router_pick_directory_server (for directory guard)
      |- router_pick_directory_server_impl (with fallback)
|- populate_live_entry_guards (filters out not live entry guards)
|- (some retry logic to make sure there is enough live entry guards)
|- node_sl_choose_by_bandwidth (from live entry guards)
```

I will document all the conditions/constraints I find in this issue, so we can keep track (and discuss whether they make sense or not). I'll also document relevant config options that may change the behaviour of `choose_random_entry_impl`.

**Comment by tcz001** [comment]
```
choose_random_entry
|- circ->build_state from the onion_extend_cpath(circ) 
   (ignored now, which should be used to exclude chosen_exit&exit_family and 
    need_uptime&need_capacity flags these entry_flags will later be used to 
    populate_live_entry_guards()->entry_is_live())
|- entry_guards_set_from_config (load options->EntryNodes)
|- pick_entry_guards 
   (this should call a entry_guards_changed to save state file)
  |- add_an_entry_guard
     (IMPORTANT: which used to be called both in pick_entry_guards and learned_bridge_descriptor)
    |- choose_good_entry_server 
     (for entry guard, but we have this in onion_extend_cpath, a recursive call as part of           
      onion_extend_cpath->
         choose_good_entry_server->
            choose_random_entry->
               pick_entry_guards->
                 add_an_entry_guard->
                    choose_good_entry_server)
      |- exit point of recursive loop
          (To get out of this is to meet: entry_list_is_constrained(options) ||
           len(entry_guards) >= num_needed)
      |- router_choose_random_node (alternative path when UseEntryGuards = 0)
    |- router_pick_directory_server (for directory guard)
      |- router_pick_directory_server_impl (with fallback)
|- populate_live_entry_guards (filters out not live entry guards)
|- (some retry logic to make sure there is preferred_min live_entry_guards chosen
    and fallback regardless of need_uptime&need_capacity)
|- node_sl_choose_by_bandwidth (from live entry guards when entry_list_is_constrained(options))
```

**Comment by tcz001** [comment]
So I think the `choose_random_entry_impl` is the right place to put most of the logic (since it has the fewest callers compared with other steps of recursive loop), but we may need the cpath state to filter out the sampled guards, and also migrate `add_an_entry_guard` logics to our proposal.

**Comment by juniorz** [comment]
Do you mean filtering things from the sampled sets? Why not rejecting
the chosen guard after the NEXT() returns something you can use?

This is how we are doing when for_directory = 1, but the chosen guard is
not a directory guard.

On 3/23/16 16:29, Fan Jiang Torchz wrote:

> So I think the |choose_random_entry_impl| is the right place to put most
> of the logic (since it has the fewest callers compared with other steps
> of recursive loop), but we may need the cpath state to filter out the
> chosen sampled guards, and also migrate |add_an_entry_guard| logic to
> our proposal.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/twstrike/tor_for_patching/issues/3#issuecomment-200551567

## 

_Reinaldo de Souza Jr_ | Software Developer
_Thought_Works Brasil

GPG: E0FD 0487 5CAC 4200 EF25 098A 9FA3 789F 0615 5999

**Comment by tcz001** [comment]
Yep, considering the on_new_consensus don't have those flags, we probably should filter after selection

**Comment by juniorz** [comment]
I'm afraid that if we ignore the guard after outside of `NEXT()` we might have an infinite loop if the guard is in `USED_GUARDS`, for example, unless we mark it somehow as ignored (sigh).
