### ISSUE TITLE
How should integration with ReachableAddresses (FascistFirewall) be?

### ISSUE THREAD

**Issue by juniorz** [twstrike/tor_for_patching#6]
`ReachableAddresses` (and `ReachableORAddresses`) tells tor the list of IP addresses and ports that your firewall allows you to connect to.

How should this influence the utopic / dystopic samples?

Option (a): "utopic guards" meaning guards reachable from an unrestricted network.

In this case "dystopic guards" may mean guards reachable by `ReachableAddresses`, defaulting to `accept *:80, accept *:443`.

Option (b): "utopic guards" meaning guards reachable by your OR given what you know about your firewall.

In this case `ReachableAddresses` should restricts the utopic guards, because you know you are not under an unrestricted network and ignoring `ReachableAddresses` will make you fail every time you choose a guard not matching `ReachableAddresses`.

In this case, "dystopic guards" may not make sense unless `ReachableAddresses` includes ports `80` or `443` for some IP address.

I'm not sure how realistic/relevant is this scenario for what we want to achieve with the `utopic` vs `dystopic` guards idea.

I suspect option (a) is what we want, and we just need a better definition for "utopic" and "dystopic" guards that takes this property into account. The spec currently defines "dystopic conditions" as:

> when a firewall is in place that blocks all ports except for potentially port 80 and 443.

Another issue is whether we should look at `ReachableAddresses` to determine if we are in a dystopic condition or always try to guess (by failing to connect to `SAMPLE_SET_THRESHOLD` utopic guards). The former could help reducing the time to connect when `ReachableAddresses` is set.

**Comment by juniorz** [comment]
Discussion in b37e78c58ec3bda6a57180b46b2aa258a4b4f890 suggests option (a).

Whether using the existence of `ReachableAddresses` to determine a dystopic condition is still an open question.

**Comment by juniorz** [comment]
See: a80472c

**Comment by tcz001** [comment]
I'm concerning when ReachableAddresses exists the percentage of sampled dystopic guards may not be a good idea, especially when it can be ip addresses.

**Comment by juniorz** [comment]
Why not?

I don't see a problem because `SAMPLE_SET_THRESHOLD` has the purpose of limiting the number of guards we are exposed to, and in this case it still works for this purpose.

I agree we might end up with a very small fraction of the total (unrestricted) guards, but I can't see a strategy to increase this number when it is too small comparing to the total of guards (specially, what would "too small" be?).

**Comment by tcz001** [comment]
for example if you have only hands of ip to use, 2% will be none

**Comment by tcz001** [comment]
and the reason of using this option probably be a special case when people notice they are in FascistFirewall and did many research on that.

**Comment by tdruiva** [comment]
This is probably covered by `fascist_firewall_allows_node`.

**Comment by tdruiva** [comment]
Have some variables that controls the ReachableAddresses, `reachable_or_addr_policy` and  `reachable_dir_addr_policy`. 
So basically we're using:
- `entry_is_live` to check if we can use a entry as guard
- `entry_is_live` calls `fascist_firewall_allows_node` to check if we can use this node based in some configurations, and ReachableAddresses is included in this check.

So we already are filtering out who not fits in our necessity but we should keep in mind that for directory (#2) `entry_is_live` have different behavior.

**Comment by tdruiva** [comment]
We could create simulation for this kind of scenario, when user have ReachableAddresses.
