### ISSUE TITLE
To expand SAMPLED_GUARDS

### ISSUE THREAD

**Issue by tdruiva** [twstrike/tor_for_patching#9]
We should have at least MINIMUM_FILTERED_SAMPLE_SIZE for FILTERED_SAMPLED.
If needed, we can expand SAMPLED_GUARDS len until MAXIMUM_SAMPLE_SIZE_THRESHOLD to try to keep filling FILTERED_SAMPLED.

https://github.com/twstrike/torspec/blob/review/proposals/259-guard-selection.txt#L343

**Comment by iapazmino** [comment]
See from 669c674 to a096b58
